# Generated by Django 4.2 on 2025-07-17 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('palace_theme', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('palace_image', models.ImageField(blank=True, null=True, upload_to='palaces/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=32)),
                ('complexity', models.IntegerField()),
                ('palace_layer', models.CharField(max_length=32)),
                ('is_completed', models.BooleanField(default=False)),
                ('layer_image', models.ImageField(blank=True, null=True, upload_to='layers/')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.dailysession')),
            ],
        ),
    ]
