# Generated by Django 4.2 on 2025-07-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="palace_image",
            field=models.ImageField(blank=True, null=True, upload_to="palaces/"),
        ),
    ]
