# Generated by Django 4.2 on 2025-07-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_palace_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="complete_palace_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="complete_palaces/"
            ),
        ),
    ]
