# Generated by Django 4.2 on 2025-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_complete_palace_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="palace_layer",
        ),
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
