# Generated by Django 4.2 on 2025-07-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_palace_layer_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_estimate',
            field=models.IntegerField(blank=True, help_text='Estimated time to complete in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(),
        ),
    ]
