# Generated by Django 4.2 on 2025-07-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_time_estimate_alter_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
