# Generated by Django 4.2 on 2025-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='layer_revealed_image',
            field=models.ImageField(blank=True, help_text='Image showing only this layer revealed', null=True, upload_to='layer_images/'),
        ),
    ]
