# Generated by Django 4.2 on 2025-07-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_layer_revealed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='layer_image',
            field=models.ImageField(blank=True, null=True, upload_to='palaces/layers/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='layer_revealed_image',
            field=models.ImageField(blank=True, help_text='Image showing only this layer revealed', null=True, upload_to='palaces/revealed/'),
        ),
    ]
